//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resourceA.rc
//
#define _USING_V110_SDK71_              1
#define IDOK_RIGID                      4
#define IDOK_SPRING_FIX                 5
#define IDOK_SPRING_MOVE                6
#define IDOK_FIXED                      7
#define IDI_ICON_BIG                    101
#define IDD_PANEL_DIALOG                103
#define IDD_DIALOG_2D_PLOT              104
#define IDD_DIALOG_PLOT_3D              106
#define IDD_DIALOG_3D_PLOT              106
#define IDD_DIALOG_INITPARAM            108
#define IDD_DIALOG_INFO                 109
#define IDB_BITMAP1                     112
#define IDD_PANEL_DIALOG1               115
#define IDB_BITMAP2                     118
#define IDD_DIALOG_DX3D                 120
#define IDD_PANEL_DIALOG_HOMEO          129
#define IDD_OPTIMIZER_DIALOG            130
#define IDB_BITMAP3                     132
#define IDD_DIALOG_SELECT_ROBOT         136
#define IDD_DIALOG_OUTPUT_BIG           142
#define IDD_DIALOG_2D_MAP               143
#define IDI_ICON_SMALL                  144
#define IDB_ROBOT_IMAGE_S               151
#define IDI_ICON_OPTIMISER              157
#define IDB_BITMAP_EA                   158
#define IDC_BUTTON_EXIT                 1000
#define IDC_BUTTON_3D                   1001
#define IDC_BUTTON_ONESTEP              1002
#define IDC_EDIT_STATUS1                1003
#define IDC_EDIT_STATUS2                1004
#define IDC_BUTTON_GOSTEP               1005
#define IDC_BUTTON_2D                   1006
#define IDC_BUTTON_RECOMPOSE            1007
#define IDC_BUTTON_RESET                1008
#define IDC_BUTTON_INCREASE             1009
#define IDC_BUTTON_GLOUT                1010
#define IDC_BUTTON_DECREASE             1011
#define IDC_BUTTON_EXIN_RESET           1012
#define IDC_BUTTON_NNVIEW               1013
#define IDC_BUTTON_GLOUT_ALL            1014
#define IDC_EDIT_RENDER                 1015
#define IDC_BUTTON_SAVE                 1015
#define IDC_EDIT_OUTPUT                 1016
#define IDC_EDIT_STATUS3                1016
#define IDC_EDIT_PLOT_3D                1017
#define IDC_BUTTON_LOAD                 1017
#define IDC_BUTTON_EXINTYPE             1018
#define IDC_BUTTON_LOCKCAM              1019
#define IDC_BUTTON_INITPARAM            1019
#define IDC_BUTTON_INFO                 1020
#define IDC_BUTTON_BACKGROUND           1020
#define IDC_EDIT_OUTIDX                 1021
#define IDC_BUTTON_VIEW_WIDE            1021
#define IDC_BUTTON_WIDE                 1021
#define IDC_BUTTON_SIMPLIFY             1021
#define IDC_BUTTON_GRAPH_UP             1021
#define IDC_BUTTON_TEXT_ALPHAWEIGHT     1021
#define IDC_BUTTON_VIEW_SMALL           1022
#define IDC_BUTTON_SMALL                1022
#define IDC_EDIT_EXINIDX                1022
#define IDC_BUTTON_SAMPLING_OK          1022
#define IDC_BUTTON_SNAPSHOT             1022
#define IDC_BUTTON_SELECT_ADD           1022
#define IDC_BUTTON_VIEW_UP              1023
#define IDC_EDIT_EXINTYPE               1023
#define IDC_BUTTON_SETXY                1023
#define IDC_BUTTON_ONOFF                1023
#define IDC_BUTTON_VIEW_WRITE           1023
#define IDC_BUTTON_VIEW_DOWN            1024
#define IDC_BUTTON_VIEW_L               1024
#define IDC_EDIT_EXINADDV               1024
#define IDC_BUTTON_SET_PLOTMAX          1024
#define IDC_BUTTON_SAMPLING             1024
#define IDC_BUTTON_GLOUT_ALL_CLOSE      1025
#define IDC_BUTTON_OUTPUTKINDOK         1025
#define IDC_BUTTON_DAMAGE               1025
#define IDC_BUTTON_IS_OFFSET            1025
#define IDC_BUTTON_SELECT_DEL           1025
#define IDC_BUTTON_VIEW_C               1026
#define IDC_BUTTON_ROBOT3D              1026
#define IDC_BUTTON_WINGTIP              1026
#define IDC_BUTTON_VIEW_R               1027
#define IDC_BUTTON_ROBOT2D              1027
#define IDC_BUTTON_JOINTOUT             1027
#define IDC_BUTTON_INTERMIT             1027
#define IDC_BUTTON_VIEW_U               1028
#define IDC_BUTTON_SELECT_ROBOT         1028
#define IDC_BUTTON_DXTEXT               1028
#define IDC_BUTTON_VIEW_D               1029
#define IDC_EDIT_STATUS5                1029
#define IDC_EDIT_STATUS4                1029
#define IDC_BUTTON_INCREASE_NODEIDX     1029
#define IDC_BUTTON_EVAL_ONOFF           1029
#define IDC_BUTTON_DECREASE_NODEIDX     1030
#define IDC_BUTTON_BGCOLOR              1030
#define IDC_BUTTON_INCREASE_NODEIDX2    1031
#define IDC_BUTTON_OUTPUTKINDOK2D       1031
#define IDC_BUTTON_SET_MAXPLOT          1031
#define IDC_BUTTON_TEXT_SENSEADAPT      1031
#define IDC_BUTTON_DECREASE_NODEIDX2    1032
#define IDC_EDIT_PLOT_MAX               1032
#define IDC_BUTTON_TEXT_ANGVELTORQ      1032
#define IDC_BUTTON_2D_PORTRAIT          1033
#define IDC_BUTTON_ADDXY                1033
#define IDC_BUTTON_TEXT_ALPHA_IDX_UP    1033
#define IDC_BUTTON_3D_PORTRAIT          1034
#define IDC_BUTTON_TEXT_ALPHA_IDX_DOWN  1034
#define IDC_BUTTON_VIEW_WIDE_2          1034
#define IDC_EDIT_MIN_LRATE              1035
#define IDC_EDIT_JOINTOUTIDX            1035
#define IDC_BUTTON_DELXY                1035
#define IDC_BUTTON_Z                    1035
#define IDC_EDIT_MAX_LRATE              1036
#define IDC_BUTTON_JOINTOUT_ALL         1036
#define IDC_EDIT_JOINTOUTIDX2           1036
#define IDC_BUTTON_IS_SENSOR            1036
#define IDC_EDIT_STATUS_HOMEO1          1037
#define IDC_EDIT_STATUS_HOMEO           1037
#define IDC_BUTTON_IS_LEADINGPOINT      1037
#define IDC_CHECK_GORAUD                1038
#define IDC_BUTTON_ADD_ALL              1038
#define IDC_RADIO_LAND                  1039
#define IDC_BUTTON_ISEXPLORE            1039
#define IDC_CHECK_READ_INIT             1039
#define IDC_BUTTON_HW_ROBOT             1039
#define IDC_BUTTON_ADD_ALL2             1039
#define IDC_BUTTON_ADD_ALL_SPRING       1039
#define IDC_BUTTON_GLCLEAR              1039
#define IDC_BUTTON_COLOR                1039
#define IDC_RADIO_WATER                 1040
#define IDC_LIST_MOTOR_STATUS           1040
#define IDC_BUTTON_FLIP_OSC             1040
#define IDC_CHECK_HW_THREAD             1040
#define IDC_BUTTON_VIEW_SMALL_2         1040
#define IDC_RADIO_AIR                   1041
#define IDC_LIST_BODY_STATUS            1041
#define IDC_BUTTON_LEARN                1041
#define IDC_BUTTON_OSC_AND_ALPHA        1041
#define IDC_RADIO_2DROBOT               1042
#define IDC_BUTTON_GLOUT_ALL_CLOSE2     1042
#define IDC_CHECK_LEARN_DOYA            1042
#define IDC_BUTTON_IS_INITPOINT         1042
#define IDC_RADIO_AIR2                  1043
#define IDC_BUTTON_INPUT_DISPLAY        1043
#define IDC_CHECK_LEARN_DOYA_ALPHA      1043
#define IDC_STATIC_LINETRACK_STATUS     1044
#define IDC_BUTTON_INCREASE_JOINTIDX    1044
#define IDC_CHECK_LEARN_SENSORCUT       1044
#define IDC_CHECK_HOMEO                 1045
#define IDC_BUTTON_DECREASE_JOINTIDX    1045
#define IDC_CHECK_LEARN_DOYA_ALPHA_RESET 1045
#define IDC_CHECK_OPTIMIZE              1046
#define IDC_EDIT1                       1046
#define IDC_BUTTON_GLOUT_CUSTOM         1046
#define IDC_CHECK_PLASTIC               1046
#define IDC_BUTTON_INCREASE_JOINTIDX2   1046
#define IDC_EDIT_WRITE_ROBOT            1046
#define IDC_EDIT_SS_INTERVAL            1046
#define IDC_EDIT_PLOT1D_X               1046
#define IDC_CHECK_BE_RANDOM             1047
#define IDC_BUTTON_JOINTOUT_CUSTOM      1047
#define IDC_BUTTON_DECREASE_JOINTIDX2   1047
#define IDC_EDIT_WRITE_EFFICIENCY       1047
#define IDC_CHECK_NOROBOT               1047
#define IDC_CHECK_GOTTWALD              1047
#define IDC_CHECK_RANDOM                1048
#define IDC_EDIT_WRITE_NEURON           1048
#define IDC_SENSE_CPG_ADAPT             1048
#define IDC_UNUSED                      1048
#define IDC_RADIO_Y                     1049
#define IDC_BUTTON_ROBOT_FILE           1049
#define IDC_BUTTON_OUTPUT_DISPLAY       1049
#define IDC_EDIT_WRITE_SENSO            1049
#define IDC_EXT_SPNET                   1049
#define IDC_EDIT_DURA                   1049
#define IDC_RADIO_DY                    1050
#define IDC_BUTTON_REPEAT_MODE          1050
#define IDC_BUTTON_REPEATMODE_SET       1050
#define IDC_EDIT_WRITE_OSCCON           1050
#define IDC_EDIT_DZ2                    1050
#define IDC_EXT_SPNET2                  1050
#define IDC_CHECK_SHARED_MEMORY         1050
#define IDC_RADIO_FR                    1051
#define IDC_BUTTON_DOYA_WEIGHT          1051
#define IDC_EDIT_WRITE_RAWSEN           1051
#define IDC_BUTTON_MULTI_OUT            1051
#define IDC_CHECK_WRITE_INIT            1051
#define IDC_BUTTON_WEIGHT_2D_MAP        1052
#define IDC_CHECK_RECORD                1052
#define IDC_RADIO_TERRESTRIAL           1053
#define IDC_BUTTON_IMG_PTRN             1053
#define IDC_RADIO_AQUATIC               1054
#define IDC_BUTTON_OSCIL_CTRNN_DISPLAY  1054
#define IDC_RADIO_NO_ROBOT              1054
#define IDC_RADIO_AERIAL                1055
#define IDC_RADIO1                      1055
#define IDC_RADIO_2D_FIN4               1055
#define IDC_RADIO_RIGID                 1055
#define IDC_RADIO_2D                    1056
#define IDC_RADIO2                      1056
#define IDC_RADIO_2D_FIN8               1056
#define IDC_RADIO_SPRING_FIX            1056
#define IDC_RADIO3                      1057
#define IDC_RADIO_QUAD                  1057
#define IDC_RADIO_2D2                   1057
#define IDC_RADIO_NO_ENV                1057
#define IDC_RADIO_SPRING_MOVE           1057
#define IDC_RADIO4                      1058
#define IDC_RADIO_FULL_WING             1058
#define IDC_RADIO_FIXED                 1058
#define IDC_RADIO_DZ_STABLE             1058
#define IDC_RADIO5                      1059
#define IDC_RADIO_FEATHER_WING          1059
#define IDC_STATIC_LOOP_MODE            1059
#define IDC_RADIO_RIGID2                1059
#define IDC_RADIO_DZ_EVAL               1059
#define IDC_RADIO_VOXEL                 1059
#define IDC_RADIO_HEX                   1060
#define IDC_STATIC_DURATION             1060
#define IDC_RADIO_DZ_EVAL2              1060
#define IDC_RADIO_DZ_CHAOS              1060
#define IDC_RADIO_SPNET_MOVE2           1060
#define IDC_RADIO_QUAD2                 1061
#define IDC_CHECK_SHARED_MEMORY3        1061
#define IDC_CHECK_PLAYBACK              1061
#define IDC_RADIO_TRI                   1062
#define IDC_BUTTON_RM                   1062
#define IDC_RADIO_2D_FIN2               1063
#define IDC_RADIO_STAR                  1064
#define IDC_BUTTON_VIEW_X_WIDE          1064
#define IDC_RADIO_QUAD3                 1065
#define IDC_BUTTON_VIEW_X_SMALL         1065
#define IDC_BUTTON_VIEW_Y_WIDE          1066
#define IDC_RADIO_HW                    1066
#define IDC_BUTTON_VIEW_Y_SMALL         1067
#define IDC_STATIC_SAMPLE_STATUS        1068
#define IDC_RADIO_SPRING                1068
#define IDC_STATIC_IS_GAIN              1070
#define IDC_BORDER_QUIT                 1093
#define IDC_COMBO_RIGID                 1097
#define IDC_COMBO_SPRING_FIX            1098
#define IDC_COMBO_SPRING_MOVE           1099
#define IDC_COMBO_FIXED                 1100
#define IDC_COMBO_FIXED2                1101
#define IDC_COMBO_EVAL                  1101
#define IDC_COMBO_FIXED3                1102
#define IDC_COMBO_VOXEL                 1102
#define IDC_COMBO_SELECT                1145
#define IDC_LIST_DATA                   1146
#define IDC_BUTTON_GRAPH_DOWN           1147
#define IDC_BUTTON_QUIT2                1151
#define IDC_CHECK_HISTORIC              1152
#define IDC_CHECK_GL_CLEAR              1153
#define IDC_STATIC_GROUP                1154
#define IDC_CHECK_GL_GRID               1155
#define IDC_BUTTON_ADDXYZ               1156
#define IDC_BUTTON_DELXYZ               1157
#define IDC_CHECK_LOCK_CAM              1158
#define IDC_EDIT_PLOT2D_X               1161
#define IDC_EDIT_PLOT2D_Y               1162
#define IDC_EDIT_PLOT3D_X               1163
#define IDC_EDIT_PLOT3D_Y               1164
#define IDC_EDIT_PLOT3D_Z               1165
#define IDC_CHECK1                      1175
#define IDC_CHECK_LOOPDELAY             1175

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1176
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
